#!/usr/bin/env python3
"""
contexia-node — CLI for setting up and managing local Contexia nodes.

Usage:
    contexia-node init --company "Corp A" --location envigado
    contexia-node status
    contexia-node sync
    contexia-node teardown

The CLI generates a ready-to-run .env.node file and (optionally) registers
the node with the central Contexia API by creating a Supabase org row.

MVP (2026-05-27):
    - `init` writes .env.node + prints next-step instructions.
    - Other commands are stubs returning canned responses.
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path
from datetime import datetime


def _slugify(text: str) -> str:
    """Lowercase, ASCII-only, hyphenated."""
    import re
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")


def cmd_init(args: argparse.Namespace) -> int:
    """Create a fresh node config."""
    company_slug = _slugify(args.company)
    location_slug = _slugify(args.location)
    node_id = f"node-{location_slug}-{company_slug}"

    env_path = Path(args.output or f".env.{node_id}")
    if env_path.exists() and not args.force:
        print(f"[ERROR] {env_path} already exists. Use --force to overwrite.", file=sys.stderr)
        return 1

    encryption_key = secrets.token_urlsafe(32)
    nas_secret = secrets.token_urlsafe(16)

    env_content = f"""# Generated by contexia-node init at {datetime.now().isoformat()}
# Company: {args.company}
# Location: {args.location}
# Node ID: {node_id}

N8N_HOST=localhost
N8N_WEBHOOK_URL=http://localhost:5678/
N8N_ENCRYPTION_KEY={encryption_key}

CONTEXIA_API_URL={args.api_url}
CONTEXIA_CLIENT_ID={node_id}

NAS_ACCESS_KEY=contexianodos
NAS_SECRET_KEY={nas_secret}
"""

    env_path.write_text(env_content, encoding="utf-8")

    print(f"[OK] Node config written to {env_path}")
    print(f"     Node ID:  {node_id}")
    print(f"     Company:  {args.company}")
    print(f"     Location: {args.location}")
    print()
    print("Next steps:")
    print(f"  1. cp {env_path} infrastructure/nodos/.env.node")
    print("  2. cd infrastructure/nodos")
    print("  3. docker compose --env-file .env.node up -d")
    print(f"  4. Register node in central API: POST {args.api_url}/nodes (manual for MVP)")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    """Show node status (stub for MVP)."""
    print("[STUB] Node status check — not yet implemented")
    print("       Will check: n8n health, NAS connectivity, central API reachability")
    return 0


def cmd_sync(args: argparse.Namespace) -> int:
    """Sync node state with central API (stub for MVP)."""
    print("[STUB] Node sync — not yet implemented")
    return 0


def cmd_teardown(args: argparse.Namespace) -> int:
    """Tear down node and remove local data (stub for MVP)."""
    print("[STUB] Teardown — run manually: docker compose down -v")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="contexia-node",
        description="Manage a local Contexia node (n8n + NAS + central API tunnel).",
    )
    sub = p.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="Generate node config")
    p_init.add_argument("--company", required=True, help='Company name (e.g., "Corp A")')
    p_init.add_argument("--location", required=True, help="Location slug (e.g., envigado)")
    p_init.add_argument("--api-url", default="https://api.contexia.online/api/v1",
                        help="Central Contexia API URL")
    p_init.add_argument("--output", help="Output path for .env file (default: .env.<node-id>)")
    p_init.add_argument("--force", action="store_true", help="Overwrite existing file")
    p_init.set_defaults(func=cmd_init)

    p_status = sub.add_parser("status", help="Show node status")
    p_status.set_defaults(func=cmd_status)

    p_sync = sub.add_parser("sync", help="Sync with central API")
    p_sync.set_defaults(func=cmd_sync)

    p_teardown = sub.add_parser("teardown", help="Stop node and remove data")
    p_teardown.set_defaults(func=cmd_teardown)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
