// lib/ciiuData.ts
// Selección de códigos CIIU comunes en Colombia (V4 AC)

export interface CIIU {
  code: string;
  description: string;
}

export const CIIU_LIST: CIIU[] = [
  { code: "1011", description: "Procesamiento y conservación de carne y productos cárnicos" },
  { code: "1081", description: "Elaboración de azúcar" },
  { code: "1089", description: "Elaboración de otros productos alimenticios n.c.p." },
  { code: "1090", description: "Elaboración de alimentos preparados para animales" },
  { code: "1104", description: "Elaboración de bebidas no alcohólicas" },
  { code: "1392", description: "Confección de artículos con materiales textiles" },
  { code: "1410", description: "Confección de prendas de vestir" },
  { code: "1512", description: "Fabricación de artículos de viaje, bolsos de mano" },
  { code: "1811", description: "Actividades de impresión" },
  { code: "2023", description: "Fabricación de jabones y detergentes, preparados para limpiar" },
  { code: "2100", description: "Fabricación de productos farmacéuticos" },
  { code: "2511", description: "Fabricación de productos metálicos para uso estructural" },
  { code: "3110", description: "Fabricación de muebles" },
  { code: "3250", description: "Fabricación de instrumentos y suministros médicos" },
  { code: "3312", description: "Mantenimiento y reparación de maquinaria y equipo" },
  { code: "4111", description: "Construcción de edificios residenciales" },
  { code: "4321", description: "Instalaciones eléctricas" },
  { code: "4520", description: "Mantenimiento y reparación de vehículos automotores" },
  { code: "4530", description: "Comercio de partes, piezas y accesorios para vehículos" },
  { code: "4610", description: "Comercio al por mayor a cambio de una retribución" },
  { code: "4631", description: "Comercio al por mayor de productos alimenticios" },
  { code: "4642", description: "Comercio al por mayor de prendas de vestir" },
  { code: "4644", description: "Comercio al por mayor de productos farmacéuticos" },
  { code: "4652", description: "Comercio al por mayor de equipo, partes y piezas electrónicas" },
  { code: "4659", description: "Comercio al por mayor de otros tipos de maquinaria y equipo" },
  { code: "4663", description: "Comercio al por mayor de materiales de construcción" },
  { code: "4711", description: "Comercio al por menor en establecimientos no especializados" },
  { code: "4719", description: "Comercio al por menor de otros productos en establecimientos no especializados" },
  { code: "4723", description: "Comercio al por menor de carnes y productos cárnicos" },
  { code: "4741", description: "Comercio al por menor de computadores, equipo periférico" },
  { code: "4752", description: "Comercio al por menor de artículos de ferretería" },
  { code: "4754", description: "Comercio al por menor de electrodomésticos" },
  { code: "4761", description: "Comercio al por menor de libros, periódicos y artículos de papelería" },
  { code: "4771", description: "Comercio al por menor de prendas de vestir y sus accesorios" },
  { code: "4772", description: "Comercio al por menor de todo tipo de calzado" },
  { code: "4773", description: "Comercio al por menor de productos farmacéuticos y medicinales" },
  { code: "4781", description: "Comercio al por menor de alimentos, bebidas y tabaco en puestos de venta móviles" },
  { code: "4791", description: "Comercio al por menor realizado a través de Internet" },
  { code: "4799", description: "Otros tipos de comercio al por menor no realizado en establecimientos" },
  { code: "4923", description: "Transporte de carga por carretera" },
  { code: "5511", description: "Alojamiento en hoteles" },
  { code: "5611", description: "Expendio a la mesa de comidas preparadas" },
  { code: "5613", description: "Expendio de comidas preparadas en cafeterías" },
  { code: "5630", description: "Expendio de bebidas alcohólicas para el consumo dentro del establecimiento" },
  { code: "5811", description: "Edición de libros" },
  { code: "5911", description: "Actividades de producción de películas cinematográficas" },
  { code: "6110", description: "Actividades de telecomunicaciones alámbricas" },
  { code: "6120", description: "Actividades de telecomunicaciones inalámbricas" },
  { code: "6201", description: "Actividades de desarrollo de sistemas informáticos" },
  { code: "6202", description: "Actividades de consultoría informática" },
  { code: "6311", description: "Procesamiento de datos, hospedaje y actividades relacionadas" },
  { code: "6411", description: "Banco Central" },
  { code: "6412", description: "Bancos comerciales" },
  { code: "6612", description: "Corretaje de valores y de contratos de productos básicos" },
  { code: "6810", description: "Actividades inmobiliarias realizadas con bienes propios o arrendados" },
  { code: "6910", description: "Actividades jurídicas" },
  { code: "6920", description: "Actividades de contabilidad, teneduría de libros, auditoría" },
  { code: "7020", description: "Actividades de consultoría de gestión" },
  { code: "7110", description: "Actividades de arquitectura e ingeniería" },
  { code: "7310", description: "Publicidad" },
  { code: "7410", description: "Actividades especializadas de diseño" },
  { code: "7420", description: "Actividades de fotografía" },
  { code: "7500", description: "Actividades veterinarias" },
  { code: "7810", description: "Actividades de agencias de empleo" },
  { code: "8010", description: "Actividades de seguridad privada" },
  { code: "8121", description: "Limpieza general interior de edificios" },
  { code: "8211", description: "Actividades combinadas de servicios administrativos de oficina" },
  { code: "8220", description: "Actividades de centros de llamadas (Call center)" },
  { code: "8230", description: "Organización de convenciones y eventos comerciales" },
  { code: "8511", description: "Educación de instituciones de educación preescolar" },
  { code: "8544", description: "Educación de instituciones de educación superior" },
  { code: "8610", description: "Actividades de hospitales y clínicas con internación" },
  { code: "8621", description: "Actividades de la práctica médica, sin internación" },
  { code: "8622", description: "Actividades de la práctica odontológica" },
  { code: "9007", description: "Actividades de espectáculos musicales en vivo" },
  { code: "9311", description: "Gestión de instalaciones deportivas" },
  { code: "9329", description: "Otras actividades de recreación y esparcimiento n.c.p." },
  { code: "9511", description: "Mantenimiento y reparación de computadores" },
  { code: "9602", description: "Peluquería y otros tratamientos de belleza" },
  { code: "9609", description: "Otras actividades de servicios personales n.c.p." },
];
